config/routes.rb
Strawberrycake::Application.routes.draw do

  root to: "pages#home"
  resources :posts

  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  delete "/logout" => "sessions#destroy", as: :logout
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, presence: true
  
  belongs_to :user

  def authored_by?(author)
    user == author
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :access_token, :name, :uid, presence: true
  validates :email, uniqueness: true

  has_many :posts, dependent: :destroy

  def self.find_or_create_with_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create
    user.assign_attributes({ name: auth.info.name, email: auth.info.email, photo_url: auth.info.image, access_token: auth.credentials.token })
    user.save!
    user
  end
end

app/controllers/application_controller.rb
# encoding: UTF-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  ensure_security_headers # See more: https://github.com/twitter/secureheaders
  helper_method :current_user, :user_signed_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      session.delete(:user_id)
      nil
  end

  def user_signed_in?
    !current_user.nil?
  end

  def authenticate!
    user_signed_in? || redirect_to(root_url, notice: "Você precisa estar autenticado...")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate!
  before_filter :set_post, only: [:edit, :update, :destroy]  

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: "Post criado com sucesso!"
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to posts_path, notice: "Post atualizado com sucesso!"
    else
      render 'edit'
    end
  end  

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post deletado com sucesso!"
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
#encoding: UTF-8
class SessionsController < ApplicationController
  
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to posts_path, :notice => "Opa! Você está online!"
  end

  def failure
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Volte em breve!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "pt"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "keywords", :content => ""}
    %meta{:name => "description", :content => ""}

    %title= yield(:title) + "Titulo aqui"

    %link{:href => "/favicon.ico", :rel => "shortcut icon"}
    = yield(:header_tags)

    = stylesheet_link_tag "application", :type => nil, :media => "all"
    = javascript_include_tag "application", :type => nil
    = csrf_meta_tags

    /[if lt IE 9]
      %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    :plain
      <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'XXXXX-XXXX']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      </script>

  %body{:id => controller.controller_name}
    #wrap
      %header
        #masthead
          /- if current_user
          /  %p
          /    = "Bem-vindo <strong>#{current_user.name}</strong> &bull; ".html_safe
          /    = link_to "Sair", logout_path
          /- else
          /  %p
          /    = link_to "Acesse com Facebook", "/auth/facebook", :id => "facebook-connect"

        #logo<
          = link_to "Logo", posts_path

        - if notice
          %p.notice
            = notice
        - if alert
          %p.alert
            = alert

      %hr
      #container
        %section{:role => "main"}
          = yield

        - if content_for?(:sidebar)
          %aside
            = yield(:sidebar)
      %hr
      %footer
        %p
          = "Copyright &copy; #{Time.zone.now.year} App".html_safe

app/views/pages/home.html.haml
OLÁ! <3

= link_to "Login com Facebook", "/auth/facebook"

app/views/posts/_form.html.haml
= form_for @post do |f|
  = f.label :title, 'Título'
  = f.text_field :title
  = f.label :content, 'Conteúdo'
  = f.text_field :content
  = f.submit 'Enviar'

app/views/posts/edit.html.haml
%h2 Editar Post

= render 'form'
  
= link_to "Voltar", posts_path 

app/views/posts/index.html.haml
- if current_user
  %h2.welcome= "Aqui está um bolo de morango pra você, #{current_user.name}"

  = link_to "Obrigado(a) pelo bolo, mas eu quero sair", logout_path, method: :delete, id: "logout-link"

  = image_tag "bolo-de-morango.jpg"

  %h2 Posts

  %p
    = link_to "Novo Post", new_post_path

  - if @posts.any?
    %table
      %thead
        %tr
          %th Título
          %th Conteúdo
          %th Ações
      %tbody 
        - @posts.each do |post|
          %tr
            %td= post.title
            %td= link_to(post.content, post)
            %td
              - if post.authored_by?(current_user)          
                = link_to "Editar", edit_post_path(post) 
                = link_to "Remover", post, :confirm => "Tem certeza?", :method => :delete
  - else
    %p Não há posts publicados

app/views/posts/new.html.haml
%h2 Novo Post

= render 'form'

  
= link_to "Voltar", posts_path 

app/views/posts/show.html.haml
%h2
  = @post.title

%p
  = @post.content 

= link_to "Voltar", posts_path 